### ISSUE TITLE
0.115b8 no go...

### ISSUE THREAD

**Issue by Repsionu** [gadgetchnnel/lovelace-home-feed-card#51] opened 2020-09-13 14:42 UTC
After testing 0.115b8 only headers show up...

**Comment by Repsionu** [comment] 2020-09-13 14:45
Also nothing in logs and HACS is OK- some kind of breaking change I missed?

**Comment by gadgetchnnel** [comment] 2020-09-13 16:50
I've not been able to reproduce this (I'm on the same version myself). Could you post your config? It may help to work out why it's not working for you.

**Comment by Repsionu** [comment] 2020-09-14 07:31
The problem has gone- it was not add-on problem but something with my NabuCasa remote access- changed it to my own server and all OK. Sorry for a false alarm and thanks for a great add-on :-)
Best regards, JR

**Comment by Repsionu** [comment] 2020-09-14 08:54
![HA  no data](https://user-images.githubusercontent.com/46962963/93064642-6e992b00-f680-11ea-9ddc-e9a445e23e52.png)
and config:

`calendars:
  - calendar.repsionu_gmail_com
entities:
  - sensor.nordpool
  - sensor.bensiin_95
  - sensor.bensiin_98
  - sensor.prugivedu
  - sensor.estonia_coronavirus_current
id_filter: ^home_feed_.*
more_info_on_tap: true
show_empty: false
title: Tegemised
type: 'custom:home-feed-card'`

More-info shows data, all entities are OK and accessible... And identing is OK, just messed up when posting :+1: 
BTW this time it is in 0.115b9

**Comment by HIT2022** [comment] 2020-09-14 09:38
Similar issue here.

![image](https://user-images.githubusercontent.com/34664460/93070174-252aea80-f644-11ea-941f-e03717aeb332.png)

**Comment by Repsionu** [comment] 2020-09-14 10:00
Absolutely no idea what is going on- just out of the blue information showed up... No restarts nor editing things...
Is it possible to increase verbose level in logs? One thing I noticed that one of my entities (covid) just updated 16 mins ago- maybe issue after restart is related to something like no changes to entities state since last restart? Go figure :-) 

And EDIT: data display disappeared again after some 1.5 hrs, did not even touch HA interface, all devices closed :-(

**Comment by gadgetchnnel** [comment] 2020-09-14 16:44
@Repsionu What types are those sensors?
When I reload the page, I briefly see similar to what you are seeing (with just icons and times) but this only lasts less then a second for me and it then displays correctly but there may be something with the config of your sensors which is causing this to take longer.

**Comment by Repsionu** [comment] 2020-09-14 17:42
sensor.estonia_coronavirus_current is from HA Covid19 integration,bensiin 98, bensiin 95 and nordpool are command line sensors coming with curl from another IOT device on local network (scrape is done outside HA),sensor.prugivedu is from garbage collection add-on.calendar is my Google one, works in other views in HA.All sensors have non-disrupted history (no breaks in data).Reload/cache clear etc. is of no-go :-(Täna, 19:44 Steven Rollason &lt;notifications@github.com&gt; Kirjutas:
@Repsionu What types are those sensors?
When I reload the page, I briefly see similar to what you are seeing (with just icons and times) but this only lasts less then a second for me and it then displays correctly but there may be something with the config of your sensors which is causing this to take longer.

**Comment by gadgetchnnel** [comment] 2020-09-17 11:31
I've been able to reproduce this when I do the following:

* Navigate to another Lovelace dashboard or another panel (e.g Developer Tools)
* Refresh the page
* Navigate back to the Lovelace dashboard with the home feed card

Relaxing the page after doing this seems to fix it.

Does that tie in with what you're seeing? I don't know why this is breaking it yet, but it should help me track it down.

**Comment by Repsionu** [comment] 2020-09-17 11:38
Yes, Same here :-( Good that You are able to reproduce it :-) Hope the mystery will be solved!-------- Original message --------From: Steven Rollason <notifications@github.com>Date: Thu, Sep 17, 2020, 14:31To: gadgetchnnel/lovelace-home-feed-card <lovelace-home-feed-card@noreply.github.com>Cc: Repsionu <jrebane@hot.ee>, Mention <mention@noreply.github.com>Subject: Re: [gadgetchnnel/lovelace-home-feed-card] 0.115b8 no go... (#51)
I've been able to reproduce this when I do the following:
Navigate to another Lovelace dashboard or another panel (e.g Developer Tools)Refresh the pageNavigate back to the Lovelace dashboard with the home feed card
Does that tie in with what you're seeing? I don't know why this is breaking it yet, but it should help me track it down.

**Comment by gadgetchnnel** [comment] 2020-09-17 14:41
I believe the issue was due to the card internally using the **ha-markdown** element for rendering content and that, sometimes, this element is not loaded and the content is therefore not rendered.

I have implemented a fix for this in the latest version (0.4.9) to make it load the element whenever it renders the feed.

Can you please update and give it a try and let me know if it works for you?

**Comment by dynasticorpheus** [comment] 2020-09-17 15:19
@gadgetchnnel  Solved the issue for me. Thanks for your efforts on this!

**Comment by gadgetchnnel** [comment] 2020-09-17 15:41
Fixed in 0.4.9

**Closed as completed by gadgetchnnel** 2020-09-17 15:41 UTC

**Comment by Repsionu** [comment] 2020-09-17 16:47
So far so good :-)Thanks for Your superb contributions to HA!Best, JR-------- Original message --------From: Steven Rollason <notifications@github.com>Date: Thu, Sep 17, 2020, 18:41To: gadgetchnnel/lovelace-home-feed-card <lovelace-home-feed-card@noreply.github.com>Cc: Repsionu <jrebane@hot.ee>, Mention <mention@noreply.github.com>Subject: Re: [gadgetchnnel/lovelace-home-feed-card] 0.115b8 no go... (#51)
Closed #51.
