### ISSUE TITLE
FR - Allow use of header / footer as per core HA cards

### ISSUE THREAD

**Issue by sparkydave1981** [gadgetchnnel/lovelace-home-feed-card#34] opened 2020-03-08 06:08 UTC
Please allow the use of Headers and Footers as per the core HA cards.

https://www.home-assistant.io/lovelace/header-footer/

I have tried but it didn't work.  Someone please let me know if this is already possible.

**Comment by gadgetchnnel** [comment] 2020-05-24 12:46
I have implemented this in the latest Beta version, 0.4.3b1. Can you please try this and let me know how you get on?

**Comment by gadgetchnnel** [comment] 2020-05-30 13:50
Closing this as resolved.

**Closed as completed by gadgetchnnel** 2020-05-30 13:50 UTC
Labels: enhancement

**Comment by sparkydave1981** [comment] 2020-07-01 08:06
Sorry for the late reply, after this has closed, but I am finding that only some images work as the header / footer and some do not (images that do work in the core cards)

**Comment by gadgetchnnel** [comment] 2020-07-15 10:39
@sparkydave1981 I'm using the same header and footer element as the the core cards, so anything which works in those should work. Do you have an example which doesn't work? That may help me to find what the issue is (could be a conflict with the styling of the card).
